import Head from 'next/head'
import App, { appName, favicon } from '@a4smanjorg5/invoida-components/App'
import HttpGet from '@/components/HttpGet'
import HttpAct from '@/components/HttpAct'
import Verifier from '@/components/Verifier'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'

const queryClient = new QueryClient()

export default function Home() {
  return (
    <>
      <Head>
        <title>{appName}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" {...favicon} />
      </Head>
      <QueryClientProvider client={queryClient}>
        <App
          Favicon={Favicon}
          HttpGet={HttpGet}
          HttpAct={HttpAct}
          Verifier={Verifier}
        />
      </QueryClientProvider>
    </>
  );
}

const Favicon = () => <></>
